<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSRDRqNh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSRDRqNh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSRDRqNh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSRDRqNh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSRDRqNh\App_KernelDevDebugContainer([
    'container.build_hash' => 'SRDRqNh',
    'container.build_id' => '5e1f9fdb',
    'container.build_time' => 1598869277,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSRDRqNh');
