<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0xFd6pL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0xFd6pL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0xFd6pL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0xFd6pL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0xFd6pL\App_KernelDevDebugContainer([
    'container.build_hash' => '0xFd6pL',
    'container.build_id' => 'd097a748',
    'container.build_time' => 1598794218,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0xFd6pL');
