<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM3Q3Ud9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM3Q3Ud9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM3Q3Ud9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM3Q3Ud9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM3Q3Ud9\App_KernelDevDebugContainer([
    'container.build_hash' => 'M3Q3Ud9',
    'container.build_id' => '8256497e',
    'container.build_time' => 1597237921,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM3Q3Ud9');
